<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LegoBL\LegoBL.csproj" />
    <ProjectReference Include="..\LegoDL_FileReader\LegoDL_FileReader.csproj" />
    <ProjectReference Include="..\LegoDL_Repository\LegoDL_Repository.csproj" />
  </ItemGroup>

</Project>
